/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '16-11-20 下午10:09' with Gradle 2.13
 *
 * @author Administrator, @date 16-11-20 下午10:09
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
